apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-service
  template:
    metadata:
      labels:
        app: api-service
    spec:
      containers:
      - name: api-service
        image: gcr.io/${{ secrets.GKE_PROJECT }}/api_service:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
